### ISSUE TITLE
Optimisation option is confusing

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#126]
What Optimisation option means? (found out by searching commit)

I think it would be better to display ComboBox with Debug and Release options along side Compile and save assembly.

| Run | Restart | Desktop x86 v | Debug v | Build | ....

if you can't call it Debug/Release then maybe 'Optimized' and 'Not Optimized'?

**Comment by aelij** [comment]
Release and Debug are **build** monikers. They define a property in MSBuild that you can use for various conditions, one beging is the compiler optimization flag, which *defaults* to optimize for Release. Since RoslynPad doesn't use any kind of build system, and this is just a representation of the compiler flag, the name is quite adequate.

Currently this is global setting, this is why it's on the bottom. The tool bar only contains stuff that control a specific document. I'm going to keep it this way for now.
