### ISSUE TITLE
Environment.Exit() causes TaskCanceledException 

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#131]
If you execute `Environment.Exit()` you get `TaskCanceledException ("a task was canceled")` with no stack trace.

**Comment by aelij** [comment]
To be frank, I'm not too concerned about that :) If you force the host process to exit, why should it matter? BTW, this is a bad way to end a script, since `Dump` calls are asynchronously dispatched to the client, and you may miss some. A simple `return;` would work better (if you're in the main script that is).

**Comment by ohadschn** [comment]
I know, but I wanted to specifically check the behavior of `Environment.Exit`. I ended up opening Visual Studio, I hope you're happy!

**Comment by aelij** [comment]
Can you elaborate? It does work, the process ends. What exactly was wrong with the scenario, besides the exception?

**Comment by ohadschn** [comment]
It didn't output my `Console.WriteLine` calls that took place before the call to `Environment.Exit`, which is what I was using to trace the behavior I was examining (in hindsight I should've written files ;]).

**Comment by aelij** [comment]
You can also add a small delay. Anyway, closing this as a no-fix.

**Comment by ohadschn** [comment]
Well I actually wanted to check if `finally` clauses are executed after an `Environment.Exit` call, so requiring a small delay for console output was not an option... Spoiler: https://stackoverflow.com/a/46180065/67824 ;)
