### ISSUE TITLE
Need some clarification with Editor Control

### ISSUE THREAD

**Issue by Nfactor26** [aelij/RoslynPad#140]
Hi Aelij,
First of all , thanks a lot for adding this feature. 

I am trying to use the editor control inside my wpf application. I referred the provided sample and everything is working like a charm. However, i am stuck at a place and need some help .

What i need to do :
When inside the script , user is trying to add a reference using #r "Assembly Name" , intelli-sense populates and shows a huge list of assemblies that he can choose from. I would like to also show assemblies from custom folders in this list. 

I was wondering how can i specify additional folders to pick this assembly list from while initializing RoslynHost . Here is my sample code where i am trying to initialize RoslynHost : 

```
 RoslynHostReferences hostReferences = RoslynHostReferences.Default;
            hostReferences = hostReferences.With(typeNamespaceImports: new[] { "Default namespaces here" },     assemblyReferences: new[]{"Additional assemblies to add that are already in memory"},
               assemblyPathReferences: new[] {"Additional assemblies to add from path "}
                );

            roslynHost = new RoslynHost(
                additionalAssemblies: new[] { Assembly.Load("RoslynPad.Roslyn.Windows"),  Assembly.Load("RoslynPad.Editor.Windows") },
                references: hostReferences
            );

```
Is there a parameter i can pass to hostReferences or roslynHost that will help me achieve this? 

Regards,
Nish26

**Comment by Nfactor26** [comment]
Also, I was wondering if there is some flag to tell editor to treat the file as a .cs file and not .csx file.
I am initializing the editor from the contents of a .cs file in one of the cases and since the content has namespace in it , the editor underlines "namespace" keyword indicating error  with message "Cannot declare namespace in script code".

**Comment by aelij** [comment]
I'll try to answer your questions, but I don't have time to give comprehensive answers. The libraries could really use docs, I know...

1. `RoslynHostReferences` has no effect on the completion list of `#r` directives. It controls the metadata references added directly to the compilation. Currently, the reference directive completion [provider](https://github.com/aelij/RoslynPad/blob/298a5032a1ec9f85f91e36bc8a000cee8b177c79/src/RoslynPad.Roslyn/Completion/Providers/ReferenceDirectiveCompletionProvider.cs) only completes GAC assemblies, absolute paths or paths that are relative to the document's location. To support an arbitrary list of paths, you'll need to write your own completion provider (or extend the current one, although it is internal). But this may not be sufficient, since the compilation needs to know how to load these assemblies, so you'll also need to provide a custom `MetadataReferenceResolver`. Currently there's no easy way of doing this using the built-in `RoslynHost` - but you can write your own.

    I can address the issue of **reference search paths** in a later version. Please open a separate issue for it.

2. Again, `RoslynHost` was designed for a specific purpose; it's not very extensible at the moment (that may change in the future). Which means it only creates documents with the Script language kind. You can create your own Roslyn workspace/solution/project/document objects and feed them to the editor (e.g. by creating a custom `IRoslynHost` or by using the `RoslynCodeEditor.CreatingDocument` event like in the REPL sample. Note that you can't use `#r` directives in non-script documents, so you can't mix namespaces and script features in the same document.

**Comment by Nfactor26** [comment]
Thanks!! I will give it a try when time permits !! Will live with it atm as it is possible to provide full path of assembly with #r in the editor and then i am able to execute the script. I will dig in to SourceFileResolver and check if i can use a relative path for execution.

**Comment by Nfactor26** [comment]
got it working as of now by configuring the ScriptOptions as follows :  
ScriptMetadataResolver scriptMetadataResolver = ScriptMetadataResolver.Default.WithBaseDirectory(AppContext.BaseDirectory);
scriptMetadataResolver = scriptMetadataResolver.WithSearchPaths("Subfolders here");
options = options.WithMetadataResolver(scriptMetadataResolver); //options is CSharpScriptOptions here

if I #r "Subfolder/anydll.dll" , Editor is generous enough to resolve this and provide intellisense.
