### ISSUE TITLE
Feature request: Overwrite closed prantesis

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#149]
If you auto insert a closing Parantesis, and the next Char I enter is also a closing Parantesis, overwrite it!

**Comment by aelij** [comment]
Already discussed in #121

**Comment by phillijw** [comment]
Every issue related to this is closed. I'm not sure how to interpret the status of this feature request. Is it still being worked on? Should I open a new ticket? Should I try to fix it myself?

**Comment by aelij** [comment]
I've researched it, and It's a very complex thing to get right. Without a proper editor that support snapshotting, it will be very hard if not impossible. So for now, just use the option to disable brace completion.

My dream is to have an OSS version of the VS editor and replace AvalonEdit :) It would greatly simplify the integration with Roslyn as well. But I'm not sure if that would ever happen, it's quite complex.

**Comment by phillijw** [comment]
Couldn't we look at the "undo state" of the editor? I was just starting to investigate it last night when I got to the point in the code where it actually did the completion. It seemed like we would have access to previous states at that point which could be utilized as a snapshot.

**Comment by aelij** [comment]
It's not that simple, you need semantic information in order to know whether you're inside a brace completion session in order to overwrite. And the undo state is very far from a real snapshot. The naive implementation would fail to do the right thing on many edge cases. I've invested many hours in this.

The point is that I've decided not to fix it, so there's no reason to keep the issue open.
