### ISSUE TITLE
Issues with System.Runtime using RoslynPad in a Net 4.6.2 WPF Application 

### ISSUE THREAD

**Issue by jogibear9988** [aelij/RoslynPad#156]
I've a Net 4.6.2 Application.

If I try to use your Nuget in this App, a reference to NetStandart2.0.1 Package is added. This Package copies System.Runtime in Version 4.1.2.0 to my bin directory. Also other DLLs Reference System.Runtime Nuget (4.3) wich includes System.Runtime in Version 4.1.1.0
My App.config has wrong dll Redirects every time I update a nuget package, because it redirects to 4.1.1.0 but in the bin directory is 4.1.2.0

Is it possible to remove the need of Referencing Netstandart 2.0.1?

**Comment by SlowLogicBoy** [comment]
![image](https://user-images.githubusercontent.com/3121637/31668918-2aa87b22-b35c-11e7-8940-2e1f8b6a9572.png)
Change references you don't want to copy to output to false

**Comment by jogibear9988** [comment]
The System.Runtime is set to "false". Also the Refernce to NetStandart2.0.1 Package does not add any refernces in the Project. It adds build steps...

**Comment by 0x53A** [comment]
@jogibear9988 can you try to add the following block to your project file? This will disable the netstandard2.0 <> net46x compatibility.

```
    <PropertyGroup>
        <ImplicitlyExpandNETStandardFacades>false</ImplicitlyExpandNETStandardFacades>
        <DisableHandlePackageFileConflicts>true</DisableHandlePackageFileConflicts>
    </PropertyGroup>
```

I've had similar issues where this "helpful" compatibility copied different versions of dlls to my build output.

Note that disabling this may break you, if you actually use a netstandard2.0 dll.

Just a shot in the dark, but maybe it helps ...

**Comment by aelij** [comment]
This is not a problem that's specific to RoslynPad, which is just a netstandard1.3 library, and so has a dependency to `NETStandard.Library (>= 1.6.1)`. NuGet just picked up the latest version; you can limit it by specifying the dependency behavior. My guess is that you have it set to **highest** (the default is **lowest**). If this is not the case, perhaps [this issue](https://github.com/dotnet/standard/issues/481) is related.

As you can see in the demo project, referencing the packages from a 4.6.2 project works just fine.

You may also want to move to using package references instead of packages.config (it's available even for the "classic" csproj).
