### ISSUE TITLE
Save supported extensions in one place

### ISSUE THREAD

**Issue by SlowLogicBoy** [aelij/RoslynPad#160]
Right now ".csx" string is hardcoded in `AbstractLoadDirectiveCompletionProvider`, `MainViewModelBase` (maybe other places too). There should be ether a setting or some constant array with supported types, because adding support for other types later might be a headache.

**Comment by aelij** [comment]
`AbstractLoadDirectiveCompletionProvider` is only applicable to .csx (there is no `#load` in a .cs file).

`MainViewModelBase` should probably use the constant `DocumentViewModel.DefaultFileExtension`, but since it needs to be without the `.` I thought it'd be easier to leave it as is. Besides, for the dialog also needs a description.

For now, let's just leave it as is. I haven't gotten requests to support .cs in RP itself (there was one request for the standalone control which doesn't use the view models at all.)
