### ISSUE TITLE
NuGet packages unavailable

### ISSUE THREAD

**Issue by tiesmaster** [aelij/RoslynPad#2]
Hi,

I saw your comment on gitter a couple days ago about this project, and was curious to try this project out, and fiddle around with it. (I know it's a pet project.)

I just tried to clone the project, run it, and step through it. However, unfortunately, NuGet restore failed on non-existing packages. I had a look on the [MyGet feed](https://www.myget.org/feed/roslyn-nightly/package/nuget/Microsoft.CodeAnalysis.CSharp), but that didn't contain the beta you referenced.

I don't know if that's the right feed, but you might consider adding the packages to git, so you can just clone it, and use it. Or maybe use something less bleeding edge ;)

Thanks!

**Comment by aelij** [comment]
Thanks for letting me know :)

Unfortunately I can't use something "less bleeding edge" because the main NuGet feed doesn't contain any of the "EditorFeatures" assemblies which make RoslynPad possible. I also wanted to avoid committing assemblies.

Too bad they delete the previous versions from that feed... I'll try to talk to someone from the Roslyn team, maybe there's a more stable feed I can use.

Eli.

**Comment by aelij** [comment]
I just pushed a commit that updates to the latest Roslyn nightly. I'll keep doing that until EditorFeatures is available on NuGet. In addition, you can download the binaries from the Releases tab.

**Comment by tiesmaster** [comment]
:+1: Cool, thnx
