### ISSUE TITLE
High memory usage / leak 

### ISSUE THREAD

**Issue by Nfactor26** [aelij/RoslynPad#278]
**Roslyn Pad v14.1**
1. Launch RolsynPad and open a .csx file
2. Take not of memory in use  i.e x mb at this point
3. Open n number of other .csx file . Memory usage is now x + n  mb 
4. Close all other .csx file except for the first one
5. Repeat steps 3 - 4

**Expected behavior :**
On closing, documents memory should reduce

**Actual behavior :** 
On opening document , memory increases , however, on closing document memory is
not released. As a result , memory usage keeps going high. This has a huge impact
where it is being used as embedded editor in host application and you are editing lots
of scripts.

**Comment by aelij** [comment]
I checked with a memory profiler and didn't see an issue. Note that checking the unmanaged memory using the task manager is not a good indication since memory is reclaimed only after a full GC.

Since you're using the embedded control, your scenario may be different, so I suggest you use a memory profiler on your app. Feed free to let me know if you can pinpoint an issue with the control.
