### ISSUE TITLE
Document Browser tab doesn't stay opened even when pinned

### ISSUE THREAD

**Issue by MarqueIV** [aelij/RoslynPad#324]
I think this is a new issue as I haven't noticed it before, but it seems ever since a recent build (maybe v15) the documents tab doesn't stay pinned open across restarts of the app.  Every time you open it, it's collapsed again.

What I would expect is whenever I pinned it, it would remember that setting, and the width it was pinned at.  Even if it wasn't pinned, I would expect the width of the 'flyout' panel to be remembered.  The less time re-setting up the UI, the better.

Note: Windows version built from sources this week.

**Comment by aelij** [comment]
Thanks for reporting this.
Tracked by external issue: https://github.com/Dirkster99/AvalonDock/issues/111

**Comment by Dirkster99** [comment]
@MarqueIV and @aelij I am having problems verifying your case but found a solution candidate as listed in the issue [Dirkster99/AvalonDock#111](https://github.com/Dirkster99/AvalonDock/issues/111). Would you guys be able to give me feedback on this please?

Thanks Dirk

**Comment by MarqueIV** [comment]
I can test it if you can tell me how I can test RoslynPad with your branch.  Never done cross-branch builds/tests before.  I'm assuming it's not that hard and it's just my mind being annoyingly scrambled thanks to the Coronavirus (ok, it's just a cold, but I'm trying to get my coworkers to stop coming by!)

**Comment by Dirkster99** [comment]
I just realized that you are using version 3.6.2 in RoslynPad and the current master branch in AvalonDock (and the linked branch above) have a breaking change introduced in version 4.0 since I removed the Xceed.Wpf.* namespace and other Xceed specific items  [see also discussion here](https://github.com/Dirkster99/AvalonDock/issues/108).

1) Assuming you can compile RoslynPad, you could download the branch linked above, compile it, and include the nuget or the AvalonDock library in RoslynPad replacing the references to your local copy.

You also would have to adjust RoslynPad for the breaking changes. The breaking changes are not much of an issue since client applications simply have to:
- refresh their references to AvalonDock 4.0 libraries
- replace "using Xceed.Wpf.AvalonDock.*" with "using AvalonDock.*"
- replace Xml prefix "http://schemas.xceed.com/wpf/xaml/avalondock" with "https://github.com/Dirkster99/AvalonDock"

This should be it for testing with the branch linked above. I would prefer this scenario because you would be testing with the current state of things.

2) Version 3.6.2 is technically not very far away from version 4.0 - so you could also test with the source code in the attached zip file where I also introduced [the candidate changes](https://github.com/Dirkster99/AvalonDock/compare/Fix_Issue_111) based on the [version 3.6.2 commit](https://github.com/Dirkster99/AvalonDock/tree/d48f783492df1e8d0e9368ab73cc7519afbf1679).

As always in live, the 2nd options is less work for you but also just an indirect test to the current master branch, but I think its still a much better test than none :-)
